---
- hosts: "all"
  tasks:
    - name: "Fix missing dir"
      file:
        path: "/usr/share/man/man1"
        state: "directory"
    - name: "Install Java"
      apt:
        update_cache: yes
        name: "openjdk-8-jre"
        state: "latest"
    - name: "Install gpg-agent"
      apt:
        update_cache: "yes"
        name: "gpg-agent"
        state: "latest"

- hosts: "all"
  vars:
    #Elasticsearch vars
    es_major_version: "7.x"
    es_version: "7.10.2"
    es_enable_xpack: False
    es_instance_name: "graylog"
    es_heap_size: "1g"
    es_config:
      node.name: "graylog"
      cluster.name: "graylog"
      http.port: 9200
      transport.tcp.port: 9300
      network.host: "127.0.0.1"
      discovery.seed_hosts: "localhost:9300"
      cluster.initial_master_nodes: "graylog"
    oss_version: True
    es_action_auto_create_index: False

    #Graylog vars
    graylog_version: 4.2
    graylog_install_java: False
    graylog_password_secret: "2jueVqZpwLLjaWxV"
    graylog_root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    graylog_http_bind_address: "{{ ansible_default_ipv4.address }}:9000"
    graylog_http_publish_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
    graylog_http_external_uri: "http://{{ ansible_default_ipv4.address }}:9000/"

  roles:
    - role: "graylog2.graylog"
      tags:
        - "graylog"
