---
- hosts: "all"
  tasks:
    - name: "Fix missing dir"
      file:
        path: "/usr/share/man/man1"
        state: "directory"
    - name: "Install packages (Ubuntu)"
      apt:
        update_cache: yes
        pkg:
          - "openjdk-8-jre"
          - "gpg-agent"
          - "curl"
        state: "latest"
      when: ansible_distribution == 'Ubuntu'
    - name: "Install packages (Debian)"
      apt:
        update_cache: yes
        pkg:
          - "openjdk-11-jre"
          - "gpg-agent"
          - "curl"
        state: "latest"
      when: ansible_distribution == 'Debian'
    - name: Install packages (Centos/Redhat)
      yum:
        name:
          - java-1.8.0-openjdk
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- hosts: "all"
  vars:
    #Elasticsearch vars
    es_major_version: "7.x"
    es_version: "7.10.2"
    es_enable_xpack: False
    es_instance_name: "graylog"
    es_heap_size: "1g"
    es_config:
      node.name: "graylog"
      cluster.name: "graylog"
      http.port: 9200
      transport.tcp.port: 9300
      network.host: "127.0.0.1"
      discovery.seed_hosts: "localhost:9300"
      cluster.initial_master_nodes: "graylog"
    oss_version: True
    es_action_auto_create_index: False

    #Graylog vars
    graylog_version: 4.2
    graylog_install_java: False
    graylog_install_enterprise_plugins: True
    graylog_install_integrations_plugins: True
    graylog_install_enterprise_integrations_plugins: True
    graylog_password_secret: "2jueVqZpwLLjaWxV"
    graylog_root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    graylog_http_bind_address: "{{ ansible_default_ipv4.address }}:9000"
    graylog_http_publish_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
    graylog_http_external_uri: "http://{{ ansible_default_ipv4.address }}:9000/"

  roles:
    - role: "graylog-ansible-role"
      tags:
        - "graylog"
