---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: graylog
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - "0.0.0.0:9000:9000/tcp"
    privileged: true
    cgroupns_mode: host
provisioner:
  name: ansible
verifier:
  name: testinfra
