---
# Galaxy's legacy namespace is Graylog2, which fails the lowercase role
# name check. Warn instead of failing.
role_name_check: 1
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: graylog
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - "0.0.0.0:9000:9000/tcp"
    privileged: true
    cgroupns_mode: host
provisioner:
  name: ansible
verifier:
  name: testinfra
