---

- hosts: all
  user: ubuntu
  sudo: yes

  vars_files:
    - defaults/main.yml
    - defaults/{{ ansible_distribution }}.yml

  tasks:
    - include: tasks/main.yml

  handlers:
    - include: handlers/main.yml
