---
- name: 'lesmyrmidons.mongodb'
  src: 'https://github.com/lesmyrmidons/ansible-role-mongodb.git'

- src: 'https://github.com/elastic/ansible-elasticsearch.git'

- name: 'jdauphant.nginx'
  src: 'https://github.com/jdauphant/ansible-role-nginx.git'
