---
- name: 'nwalke.mongodb'
  src: 'https://github.com/nwalke/ansible-role-mongodb.git'
  version: 'v2.0.0'

- name: 'ansible-elasticsearch'
  src: 'https://github.com/elastic/ansible-elasticsearch.git'
  version: '0.1.2'

- name: 'jdauphant.nginx'
  src: 'https://github.com/jdauphant/ansible-role-nginx.git'
  version: 'v2.3.1'
