---
- name: greendayonfire.mongodb
  src: https://github.com/UnderGreen/ansible-role-mongodb

- name: f500.elasticsearch
  src: https://github.com/f500/ansible-elasticsearch

- name: jdauphant.nginx
  src: https://github.com/jdauphant/ansible-role-nginx
