---

- name: "elastic.elasticsearch"
  src: "https://github.com/elastic/ansible-elasticsearch.git"
  version: "6.6.0"

- name: "jdauphant.nginx"
  src: "https://github.com/jdauphant/ansible-role-nginx.git"
  version: "v2.21.2"
