---
- name: 'lesmyrmidons.mongodb'
  src: 'https://github.com/lesmyrmidons/ansible-role-mongodb.git'
  version: 'master'

- name: 'elastic.elasticsearch'
  src: 'https://github.com/elastic/ansible-elasticsearch.git'
  version: '0.2'

- name: 'jdauphant.nginx'
  src: 'https://github.com/jdauphant/ansible-role-nginx.git'
  ersion: 'v2.7.4'
