---
- name: 'lesmyrmidons.mongodb'
  src: 'https://github.com/lesmyrmidons/ansible-role-mongodb'

- src: 'https://github.com/elastic/ansible-elasticsearch'

- name: 'jdauphant.nginx'
  src: 'https://github.com/jdauphant/ansible-role-nginx'
