---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: graylog01
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    privileged: true
    pre_build_image: true
    groups:
      - graylog_primary
  - name: graylog02
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    privileged: true
    pre_build_image: true
    groups:
      - graylog_secondary
  - name: graylog03
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    privileged: true
    pre_build_image: true
    groups:
      - graylog_secondary
  - name: elasticsearch01
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    privileged: true
    pre_build_image: true
    groups:
      - elasticsearch
  - name: elasticsearch02
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    privileged: true
    pre_build_image: true
    groups:
      - elasticsearch
  - name: elasticsearch03
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    privileged: true
    pre_build_image: true
    groups:
      - elasticsearch
provisioner:
  name: ansible
