---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: graylog01
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    published_ports:
      - "0.0.0.0:9000:9000/tcp"
    privileged: true
    pre_build_image: true
    groups:
      - graylog
  - name: graylog02
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    published_ports:
      - "0.0.0.0:9001:9000/tcp"
    privileged: true
    pre_build_image: true
    groups:
      - graylog
  - name: graylog03
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    published_ports:
      - "0.0.0.0:9002:9000/tcp"
    privileged: true
    pre_build_image: true
    groups:
      - graylog
  - name: elasticsearch01
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    privileged: true
    pre_build_image: true
    groups:
      - elasticsearch
  - name: elasticsearch02
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    privileged: true
    pre_build_image: true
    groups:
      - elasticsearch
  - name: elasticsearch03
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "graylog"
    network_mode: "graylog"
    privileged: true
    pre_build_image: true
    groups:
      - elasticsearch
provisioner:
  name: ansible
