---
- role: lean_delivery.java
  version: 7.1.0

- name: "elastic.elasticsearch"
  src: "https://github.com/elastic/ansible-elasticsearch.git"
  version: master

- name: "nginxinc.nginx"
  src: "https://github.com/nginxinc/ansible-role-nginx.git"
  version: "0.14.0"
