---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    ignore-errors: true
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  set -e
  yamllint .
  #ansible-lint .
platforms:
  - name: instance
    box: ${MOLECULE_DISTRO:-generic/ubuntu1804}
    memory: 4096
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    provider_raw_config_args:
      - 'nic_model_type = "virtio"'
      - 'disk_bus = "virtio"'
      - 'volume_cache = "none"'
      - 'storage :file, bus: "virtio", cache: "none"'
providers:
  - name: libvirt
    type: libvirt
    driver: kvm
provisioner:
  name: ansible
verifier:
  name: ansible
