- hosts: "all"
  remote_user: "ubuntu"
  become: True
  vars:

    #Graylog vars
    graylog_version: 3.3
    graylog_install_java: False
    graylog_password_secret: "cmwpyPekzbDtIqvZXx25bjw6SiQMOA64F6aKQW168e0ukqsnWqbV72d5BZAcAHqob8oVchEk8YcOQk4t4sWYbabM2sWXNOlZ"
    graylog_root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    graylog_http_bind_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:9000"
    graylog_http_publish_uri: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:9000/"
    graylog_http_external_uri: "http://localhost:9000/"

  roles:
    - role: "graylog2.graylog"
      tags:
        - "graylog"
