- hosts: "all"
  remote_user: "ubuntu"
  become: True
  vars:

    # Graylog vars
    graylog_version: 4.2
    graylog_install_java: True
    graylog_password_secret: "2jueVqZpwLLjaWxV"
    graylog_root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    graylog_http_bind_address: "{{ ansible_default_ipv4.address }}:9000"
    graylog_http_publish_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
    graylog_http_external_uri: "http://{{ ansible_default_ipv4.address }}:9000/"

  roles:
    - role: "graylog2.graylog"
      tags:
        - "graylog"
